version: '2'
services:
  web:
    image: nginx
    ports:
     - 8080:80
    volumes:
     - ./web/dist:/usr/share/nginx/html
     - ./web/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
  be:
    build: ./server
    ports:
     - "3000:3000"
    environment:
      DB_CONNECTION_STRING: mysql://root:example@db:3306/blog
