version: '2'
services:
  web:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - "be"
    command: ["npm", "start"]
    volumes:
      - './web/src:/usr/src/app/src'
    tty: true
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
  be:
    build: ./server
    ports:
      - "3000:3000"
    command: ["./wait-for-db.sh"]
    environment:
      DB_CONNECTION_STRING: mysql://root:example@db:3306/blog
